# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: "12"
          check-latest: true
      - name: Installing Node
        run: npm install
      - name: Install Surge
        run: npm i -g surge
      - name: Create Build
        run: CI=false npm run build
        # Rename the index.html file to 200.html
      - name: Rename the index.html file to 200.html
        run: sudo cp ./build/index.html ./build/200.html && sudo rm ./build/index.html
      - name: Deploy on Surge
        run: surge ./build --token ${{secrets.SURGE_TOKEN}} --domain https://serco.surge.sh
